### ISSUE TITLE
Cannot Parse Python2 Code with Python3

### ISSUE THREAD

**Issue by HenryHoggard** [Skyscanner/whispers#40]
Hey! Nice tool, just having a play and running into a couple of issues.

I'm trying to scan some code, if I use whispers with python3, I get parse errors when the code I'm trying to scan is python2, for example:

```
Traceback (most recent call last):
  File "/Users/user/.virtualenvs/path/lib/python3.9/site-packages/whispers/plugins/python.py", line 17, in pairs
    tree = astroid.parse(filepath.read_text())
  File "/Users/user/.virtualenvs/path/lib/python3.9/site-packages/astroid/builder.py", line 279, in parse
    return builder.string_build(code, modname=module_name, path=path)
  File "/Users/user/.virtualenvs/path/lib/python3.9/site-packages/astroid/builder.py", line 142, in string_build
    module = self._data_build(data, modname, path)
  File "/Users/user/.virtualenvs/path/lib/python3.9/site-packages/astroid/builder.py", line 170, in _data_build
    raise exceptions.AstroidSyntaxError(
astroid.exceptions.AstroidSyntaxError: Parsing Python code failed:
Missing parentheses in call to 'print'. Did you mean print(header)? (<unknown>, line 38)
```

I tried running whispers with python2, and I get the following build error:

```
ollecting whispers
  Using cached https://pypi.apple.com/packages/packages/db/12/9630c48c409c12cedb116d28e5e6d0402db81ec82ac6366dae9f7cfc02a1/whispers-1.3.12.tar.gz (26 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/user/.virtualenvs/path/bin/python /Users/user/.virtualenvs/path/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/kp/rn0d0qbj25gfj9sn5wg23pth0000gp/T/tmpGHkCim
       cwd: /private/var/folders/kp/rn0d0qbj25gfj9sn5wg23pth0000gp/T/pip-install-dfI8Zr/whispers
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/Users/user/.virtualenvs/path/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/Users/user/.virtualenvs/path/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/user/.virtualenvs/path/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/kp/rn0d0qbj25gfj9sn5wg23pth0000gp/T/pip-build-env-kr5PVa/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/private/var/folders/kp/rn0d0qbj25gfj9sn5wg23pth0000gp/T/pip-build-env-kr5PVa/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/kp/rn0d0qbj25gfj9sn5wg23pth0000gp/T/pip-build-env-kr5PVa/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 243, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/private/var/folders/kp/rn0d0qbj25gfj9sn5wg23pth0000gp/T/pip-build-env-kr5PVa/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 3, in <module>
      from pathlib import Path
  ImportError: No module named pathlib
```

So currently I cannot use whispers if any of the target code is python2. Is there a way in the meantime to disable python parsing and treat it as a standard file?

**Comment by adeptex** [comment]
Hey @HenryHoggard interesting finding, thanks for raising. Let me have a look. In the meantime you can exclude all python files from being scanned by editing the config, but unfortunately no way to distinguish right now between python versions.

Cheers

**Comment by HenryHoggard** [comment]
So I've found that if you are running whispers via the cli eg `whispers --config config.yml scanfolder` this issue doesn't appear.

Its only when trying to call it from python using the example on the readme:

```
from whispers.cli import parse_args
from whispers.core import load_config, run

src = "src/fileOrDir"
configfile = "config.yml"
args = parse_args([src])
args.config = load_config(configfile, src)
secrets = run(args)

```

**Comment by adeptex** [comment]
This must be because when you run it from CLI it logs the error to whispers.log. But when you do it through code, there is no error handler set on `secrets = run(args)`
It's a good improvement to have I think. Will kick some code around :)

**Comment by adeptex** [comment]
hey @HenryHoggard I've just merged this in: https://github.com/Skyscanner/whispers/pull/41 , which should solve the issues reported here. The new version is 1.4.0

I also updated how whispers should be executed from code, which is less clunky:
```python
from whispers.cli import parse_args
from whispers.core import run

src = "tests/fixtures"
configfile = "whispers/config.yml"
args = parse_args(["-c", configfile, src])
for secret in run(args):
  print(secret)
```

Thanks again for reporting. Closing this issue for now. Please feel free to open another one if you are still experiencing problems.

Cheers!
